#!/bin/bash

# Solo funciona desde cualquier distribución basada en Ubuntu 22.04 y superior.

echo "==============================="
echo " ¡Bienvenidos a Auto-Palera1n!"
echo "==============================="
echo "Elegiste iOS $1"
echo "Ingrese 1 para comenzar o 0 para salir"
read resp
if [ $resp -eq 1 ]
 then
   echo -e "\033[0;37m[*] La instalación de Dependencias puede llevar un tiempo..."
   sudo apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update > /dev/null
   sudo apt update > /dev/null
   sudo apt install git -y > /dev/null
   sudo apt-get install sudo gcc bash wget python3-pip libavahi-client-dev libusb-1.0-0 libusb-1.0-0-dev libadolc2 libusbmuxd-tools libtool usbmuxd libtool-bin autoconf automake libimobiledevice* make -y > /dev/null
   sudo pip install pyimg4 &> /dev/null
   wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb &> /dev/null
   wget https://github.com/CoocooFroggy/FutureRestore-GUI/releases/download/v1.98.2/FutureRestore-GUI-Debian-1.98.2.deb &> /dev/null
   sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb > /dev/null
   sudo dpkg -i FutureRestore-GUI-Debian-1.98.2.deb > /dev/null
   git clone https://github.com/tihmstar/libgeneral > /dev/null
   cd libgeneral
   printf "\n[*] Compilando LIBGENERAL...\n\n"
   sudo ./autogen.sh &> /dev/null
   sudo make &> /dev/null
   sudo make install &> /dev/null
   cd ..
   git clone https://github.com/tihmstar/usbmuxd2 &> /dev/null
   cd usbmuxd2
   printf "\n[*] Compilando USBMUXD2...\n\n"
   sudo ./autogen.sh &> /dev/null
   make &> /dev/null
   make install &> /dev/null
   printf "\n[+] Cependencias instaladas!\n"
   sleep 1
   systemctl stop usbmuxd
   cd ..
   echo -e "\n[*] Descargando Palera1n...\n"

   sudo git clone --recursive https://github.com/palera1n/palera1n &> /dev/null
   echo "[+] Palera1n Descargado!"
   sudo git clone --recursive https://github.com/ricardoifc/palera1n-3.0 & /dev/null
   echo "[+] Palera1n Boot Fix 3.0 de ricardoifc-iOS Descargado!"
   printf "\033[1;37m[*] Conecte su dispositivo en modo DFU y escriba los comandos a continuación\n"
   printf "\n\033[0;32mcd palera1n\n"
   printf "\033[0;32msudo ./palera1n.sh --tweaks $1 --semi-tethered (quitar --semitethered si su iphone es de 16 gbs)\n\n"
else
   echo "[*] Saindo..."
   exit
fi
